# https://railsguides.jp/configuring.html#%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E8%A8%AD%E5%AE%9A
shared:
  app_name: Taiten

development:
  app_name: Taiten (DEV)
  host: rails-dev.akoba.xyz  # 開発者ごとに変わるのは共通のファイルに書きたくない。データベースも同じか。

production:
  host: kyuuki-sample-taiten.herokuapp.com
